create table if not exists public.territories (
  id integer primary key,
  territory_name text not null,
  map_link text not null default '',
  map_image_url text not null default '',
  map_description text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  territory_id integer not null references public.territories(id) on delete cascade,
  assigned_at timestamptz not null default now()
);

create table if not exists public.system_updates (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists assignments_territory_id_idx on public.assignments(territory_id);
create index if not exists assignments_assigned_at_idx on public.assignments(assigned_at desc);

alter table public.territories enable row level security;
alter table public.assignments enable row level security;
alter table public.system_updates enable row level security;

create policy "service role manages territories"
on public.territories
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create policy "service role manages assignments"
on public.assignments
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create policy "service role manages system updates"
on public.system_updates
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
